var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/a-propos/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__47be6bcd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_af04cd84._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06d33efc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1690ee0d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__bb5349a4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_a-propos_layout_tsx_459062b7._.js")
R.c("server/chunks/ssr/_next-internal_server_app_a-propos_page_actions_267ec6fa.js")
R.m(29102)
module.exports=R.m(29102).exports
