var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/calendrier/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__95cbd636._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_3f838439._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06d33efc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1690ee0d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__bb5349a4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_calendrier_layout_tsx_9e5a58f6._.js")
R.c("server/chunks/ssr/_next-internal_server_app_calendrier_page_actions_fd71cc74.js")
R.m(56640)
module.exports=R.m(56640).exports
