var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/articles/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__679ec7cd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_240be70c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06d33efc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1690ee0d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__bb5349a4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_articles_layout_tsx_508cd24b._.js")
R.c("server/chunks/ssr/_next-internal_server_app_articles_page_actions_8e61ab48.js")
R.m(80702)
module.exports=R.m(80702).exports
